# Archivo de EJEMPLO para la configuraci\u00f3n de la Base de Datos
# Copia este archivo como 'db.properties' y rellena con tus credenciales reales.
javax.persistence.jdbc.url=jdbc:mysql://TU_SERVIDOR:TU_PUERTO/TU_BASE_DE_DATOS?serverTimezone=UTC
javax.persistence.jdbc.user=TU_USUARIO
javax.persistence.jdbc.password=TU_CONTRASE\u00d1A